name: the_handbook_of_superheroes
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.7.2
  extended_image: ^10.0.1
  flutter_easyloading: ^3.0.5
  ionicons: ^0.2.2
  lottie: ^3.3.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  carousel_slider: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  device_info_plus: ^11.4.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  google_mobile_ads: ^6.0.0

dependency_overrides:
  webview_flutter_wkwebview: '3.5.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
