name: the_handbook_of_superheroes
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  extended_image: ^8.0.2
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.8.4
  ionicons: ^0.2.2
  lottie: ^2.4.0
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  carousel_slider: ^4.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  device_info_plus: ^9.0.2
  shimmer: ^3.0.0
  flutter_animate: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
